import type { ContentItem } from './types';

export const modules: ContentItem[] = [
  {
    id: 1,
    title: 'Módulo 01 - Comece por Aqui',
    description: 'Os primeiros passos para iniciar sua jornada na saboaria artesanal com segurança e confiança.',
    image: 'https://placehold.co/600x400',
    slug: 'comece-por-aqui',
    progress: 0,
    type: 'module',
    lessons: [
      { id: 1, title: 'O que é Saboaria Artesanal?', url: 'https://www.youtube.com/watch?v=yk6sqafus0Q', completed: false, type: 'video' },
      { id: 2, title: 'Tipos de Bases e Essências', url: 'https://www.youtube.com/watch?v=ijO5hZSOZB0', completed: false, type: 'video' },
      { id: 3, title: 'Corantes Naturais e Artificiais', url: 'https://www.youtube.com/watch?v=tNevZgGJXXE', completed: false, type: 'video' },
      { id: 4, title: 'Utensílios Usados na Saboaria', url: 'https://www.youtube.com/watch?v=2rHntZ5hhvI', completed: false, type: 'video' },
      { id: 5, title: 'Precificação', url: 'https://www.youtube.com/watch?v=iSvrd6j9zUE', completed: false, type: 'video' },
    ],
  },
  {
    id: 2,
    title: 'Módulo 02 - Erros Comuns na Saboaria',
    description: 'Aprenda a evitar os erros mais comuns que iniciantes cometem e garanta o sucesso de suas receitas.',
    image: 'https://placehold.co/600x400',
    slug: 'erros-comuns-na-saboaria',
    progress: 0,
    type: 'module',
    lessons: [
      { id: 1, title: 'Introdução aos Erros Comuns na Saboaria', url: 'https://www.youtube.com/watch?v=x39O0bFVcqM', completed: false, type: 'video' },
      { id: 2, title: 'Ponto Certo da Base e Uso Correto das Essências', url: 'https://www.youtube.com/watch?v=KFG01L1nJOo', completed: false, type: 'video' },
      { id: 3, title: 'Sabonete Suando e Modo Correto de Secagem', url: 'https://www.youtube.com/watch?v=T3ZZAhqgiWg', completed: false, type: 'video' },
      { id: 4, title: 'Ressecamento e Falta de Espuma', url: 'https://www.youtube.com/watch?v=_eE288DcPNM', completed: false, type: 'video' },
    ],
  },
  {
    id: 3,
    title: 'Módulo 03 - Seu Primeiro Sabonete',
    description: 'Um passo a passo guiado para você criar seu primeiro sabonete artesanal do zero.',
    image: 'https://placehold.co/600x400',
    slug: 'seu-primeiro-sabonete',
    progress: 0,
    type: 'module',
    lessons: [
        { id: 1, title: 'Mão na Massa!', url: 'https://www.youtube.com/watch?v=vo0lwzl2aXA', completed: false, type: 'video' },
        { id: 2, title: 'Desenformando o Sabonete', url: 'https://www.youtube.com/watch?v=JRXCk7Uc8k4', completed: false, type: 'video' },
        { id: 3, title: 'Embalagem e Precificação', url: 'https://www.youtube.com/watch?v=fhmioW0P1aA', completed: false, type: 'video' },
    ],
  },
  {
    id: 4,
    title: 'Módulo 04 - Sabonetes Decorativos',
    description: 'Técnicas para transformar seus sabonetes em verdadeiras obras de arte.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonetes-decorativos',
    progress: 0,
    type: 'module',
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=KNVkPdK55d8', completed: false, type: 'video' },
        { id: 2, title: 'Fazendo o Sabonete Decorativo', url: 'https://www.youtube.com/watch?v=4NXL5wPwhCQ', completed: false, type: 'video' },
        { id: 3, title: 'Desenformando o Sabonete Decorativo', url: 'https://www.youtube.com/watch?v=w1XiezRfuDQ', completed: false, type: 'video' },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/watch?v=4A97GuZ2aOI', completed: false, type: 'video' },
    ],
  },
  {
    id: 5,
    title: 'Módulo 05 - Sabonetes Para Lembrancinhas',
    description: 'Crie sabonetes perfeitos para presentear em eventos e ocasiões especiais.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonetes-para-lembrancinhas',
    progress: 0,
    type: 'module',
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=P8pktqeEpvQ', completed: false, type: 'video' },
        { id: 2, title: 'Fazendo Nosso Sabonete', url: 'https://www.youtube.com/watch?v=AylWaIgu778', completed: false, type: 'video' },
        { id: 3, title: 'Desenformando nosso Sabonete', url: 'https://www.youtube.com/watch?v=KfQxmbhokkY', completed: false, type: 'video' },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/watch?v=oW1Pm-CO3fA', completed: false, type: 'video' },
    ],
  },
  {
    id: 6,
    title: 'Módulo 06 - Sabonete Esfoliante',
    description: 'Aprenda a fazer sabonetes que limpam e renovam a pele com ingredientes naturais.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-esfoliante',
    progress: 0,
    type: 'module',
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=Osr2NNhg4YQ', completed: false, type: 'video' },
        { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/watch?v=biKY2p7dHrU', completed: false, type: 'video' },
        { id: 3, title: 'Desenformando', url: 'https://www.youtube.com/watch?v=BaUYrLlYNC0', completed: false, type: 'video' },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/watch?v=fhtJ7Lns_sg', completed: false, type: 'video' },
    ],
  },
  {
    id: 7,
    title: 'Módulo 07 - Sabonete de Frutas',
    description: 'Incorpore o poder e os aromas das frutas em suas criações.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-de-frutas',
    progress: 0,
    type: 'module',
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=mCfs8uxxdGA', completed: false, type: 'video' },
        { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/watch?v=VaTMghE8Ugk', completed: false, type: 'video' },
        { id: 3, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/watch?v=D8TZdIWv86A', completed: false, type: 'video' },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/watch?v=xGE5VxrfdGs', completed: false, type: 'video' },
    ],
  },
  {
    id: 8,
    title: 'Módulo 08 - Sabonete Fito Energético',
    description: 'Descubra como usar a energia das plantas para criar sabonetes com propósito.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-fito-energetico',
    progress: 0,
    type: 'module',
    lessons: [
      { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=CeSBrDagGRs', completed: false, type: 'video' },
      { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/watch?v=1Licryb1ik4', completed: false, type: 'video' },
      { id: 3, title: 'Aula Pratica', url: 'https://www.youtube.com/watch?v=1Licryb1ik4', completed: false, type: 'video' },
      { id: 4, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/watch?v=1lzgaUJyaJI', completed: false, type: 'video' },
      { id: 5, title: 'Precificação', url: 'https://www.youtube.com/watch?v=dDQjI1COqe0', completed: false, type: 'video' },
    ],
  },
  {
    id: 9,
    title: 'Módulo 09 - Sabonete Terapêutico',
    description: 'Crie sabonetes com propriedades terapêuticas usando óleos essenciais e extratos naturais.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-terapeutico',
    progress: 0,
    type: 'module',
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=vfwcQQLlhog', completed: false, type: 'video' },
        { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/watch?v=Uf55mYcFb1Y', completed: false, type: 'video' },
        { id: 3, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/embed/lSTVl3PQk18', completed: false, type: 'video' },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/KDKvMYRfBTQ', completed: false, type: 'video' },
    ],
  },
  {
    id: 10,
    title: 'Módulo 10 - Sabonete Vegano',
    description: 'Aprenda a fazer sabonetes de alta qualidade sem nenhum ingrediente de origem animal.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-vegano',
    progress: 0,
    type: 'module',
    lessons: [
      { id: 1, title: 'Introdução', url: 'https://www.youtube.com/watch?v=u-NMGjMpDCg', completed: false, type: 'video' },
      { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/watch?v=_lqbshzHVEg', completed: false, type: 'video' },
      { id: 3, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/watch?v=zqmqxlvyXCI', completed: false, type: 'video' },
      { id: 4, title: 'Precificação', url: 'https://www.youtube.com/watch?v=hSttFBuI-jM', completed: false, type: 'video' },
    ],
  },
];

export const bonusContent: ContentItem[] = [
  {
    id: 11,
    title: 'Saboaria Lucrativa',
    description: 'Aprenda a transformar sua paixão por saboaria em um negócio rentável.',
    image: 'https://placehold.co/600x400',
    slug: 'saboaria-lucrativa',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Saboaria Lucrativa', url: 'https://drive.google.com/file/d/1hdxNYcYyD7j2bH1xUKPzE7rtBauCDJxo/preview', completed: false, type: 'pdf' },
    ],
  },
  {
    id: 12,
    title: 'Divulgações e Vendas',
    description: 'Estratégias para divulgar seus produtos e aumentar suas vendas.',
    image: 'https://placehold.co/600x400',
    slug: 'divulgacoes-e-vendas',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Divulgações e Vendas', url: 'https://drive.google.com/file/d/1sQxHZMRXdVSHltpVCEHR1u54czbMeY8z/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 13,
    title: 'Etiquetas Pra Imprimir',
    description: 'Modelos de etiquetas prontos para você imprimir e usar em seus produtos.',
    image: 'https://placehold.co/600x400',
    slug: 'etiquetas-pra-imprimir',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Etiquetas Pra Imprimir', url: 'https://drive.google.com/file/d/12i-prpvmCs6SyFoXao7oMB0ub7BC_4vF/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 14,
    title: 'Robô de Precificação',
    description: 'Uma ferramenta para te ajudar a precificar seus produtos de forma correta.',
    image: 'https://placehold.co/600x400',
    slug: 'robo-de-precificacao',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Robô de Precificação', url: 'https://drive.google.com/file/d/1tYBlDlFMq-EcxPOgHa2HN-v2TeeE7JVD/preview', completed: false, type: 'pdf' },
    ],
  },
     {
    id: 15,
    title: 'Produtos For Pets',
    description: 'Aprenda a fazer produtos de higiene para animais de estimação.',
    image: 'https://placehold.co/600x400',
    slug: 'produtos-para-pets',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Produtos For Pets', url: 'https://drive.google.com/file/d/1QewdEi8b4joOJy3BSC4cL9--WiXCuAnl/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 16,
    title: 'Receitas de Condicionador',
    description: 'Receitas exclusivas de condicionadores artesanais.',
    image: 'https://placehold.co/600x400',
    slug: 'receitas-de-condicionador',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Receitas de Condicionador', url: 'https://drive.google.com/file/d/1qjhn1W_cwpGwT6RKJPsvrgnzKWXCntYP/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 17,
    title: 'Lista de Fornecedores',
    description: 'Uma lista completa com os melhores fornecedores de matéria-prima.',
    image: 'https://placehold.co/600x400',
    slug: 'lista-de-fornecedores',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Lista de Fornecedores', url: 'https://drive.google.com/file/d/1IyEoho-fV98ee9lkWMRrCUZKuXZUZNOO/preview', completed: false, type: 'pdf' },
    ],
  },
    {
    id: 18,
    title: 'Lista de Materiais da Vó Rita',
    description: 'A lista de materiais essenciais que a Vó Rita usa em suas receitas.',
    image: 'https://placehold.co/600x400',
    slug: 'lista-de-materiais-da-vo-rita',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Lista de Materiais da Vó Rita', url: 'https://drive.google.com/file/d/1o0qTMKgpO4CJOFEdybTGL-P2IpHztCl3/preview', completed: false, type: 'pdf' },
    ],
  },
    {
    id: 19,
    title: 'Saboaria de Sucesso',
    description: 'Dicas e segredos para você ter sucesso no mundo da saboaria artesanal.',
    image: 'https://placehold.co/600x400',
    slug: 'saboaria-de-sucesso',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Saboaria de Sucesso', url: 'https://drive.google.com/file/d/1R1TkyqlKiILwiG8-tUhohJYIUBGg5xXO/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 20,
    title: 'Receitas de Cremes Hidratantes',
    description: 'Aprenda a fazer cremes hidratantes para o corpo e rosto.',
    image: 'https://placehold.co/600x400',
    slug: 'receitas-de-cremes-hidratantes',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Receitas de Cremes Hidratantes', url: 'https://drive.google.com/file/d/1kmveu7k-z9IaQKXH9IsP1yOe20YgEiF-/preview', completed: false, type: 'pdf' },
    ],
  },
    {
    id: 21,
    title: 'Desodorantes Naturais',
    description: 'Receitas de desodorantes naturais, sem alumínio e outros químicos.',
    image: 'https://placehold.co/600x400',
    slug: 'desodorantes-naturais',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Desodorantes Naturais', url: 'https://drive.google.com/file/d/1_c_evEXyx5IveuYEVIHwN8wJVc4olDye/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 22,
    title: 'Sabonete Liquido',
    description: 'Aprenda a fazer sabonete líquido para as mãos e para o corpo.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-liquido',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Sabonete Liquido', url: 'https://drive.google.com/file/d/1W08VYOn8N4u5SWtaKqfl5r9pGpyTiIao/preview', completed: false, type: 'pdf' },
    ],
  },
   {
    id: 23,
    title: 'Shampoo Artesanal',
    description: 'Receitas de shampoos artesanais para todos os tipos de cabelo.',
    image: 'https://placehold.co/600x400',
    slug: 'shampoo-artesanal',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Shampoo Artesanal', url: 'https://drive.google.com/file/d/1OVjbWQfp7dysEXQWiAZZfLm534aAzadJ/preview', completed: false, type: 'pdf' },
    ],
  },
  {
    id: 24,
    title: 'Sabonetes de Frutas',
    description: 'Receitas de sabonetes com polpa de frutas frescas.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonetes-de-frutas-bonus',
    progress: 0,
    type: 'bonus',
    lessons: [
      { id: 1, title: 'Sabonetes de Frutas', url: 'https://drive.google.com/file/d/1HJuw-TFZVTj7JLNox32RkGZSOPZ0DCYn/preview', completed: false, type: 'pdf' },
    ],
  },
];
