import type { ContentItem } from './types';

export const modules: ContentItem[] = [
  {
    id: 1,
    title: 'Módulo 01 - Comece por Aqui',
    description: 'Os primeiros passos para iniciar sua jornada na saboaria artesanal com segurança e confiança.',
    image: 'https://placehold.co/600x400',
    slug: 'comece-por-aqui',
    progress: 0,
    lessons: [
      { id: 1, title: 'O que é Saboaria Artesanal?', url: 'https://www.youtube.com/embed/yk6sqafus0Q', completed: false },
      { id: 2, title: 'Tipos de Bases e Essências', url: 'https://www.youtube.com/embed/ijO5hZSOZB0', completed: false },
      { id: 3, title: 'Corantes Naturais e Artificiais', url: 'https://www.youtube.com/embed/tNevZgGJXXE', completed: false },
      { id: 4, title: 'Utensílios Usados na Saboaria', url: 'https://www.youtube.com/embed/2rHntZ5hhvI', completed: false },
      { id: 5, title: 'Precificação', url: 'https://www.youtube.com/embed/iSvrd6j9zUE', completed: false },
    ],
  },
  {
    id: 2,
    title: 'Módulo 02 - Erros Comuns na Saboaria',
    description: 'Aprenda a evitar os erros mais comuns que iniciantes cometem e garanta o sucesso de suas receitas.',
    image: 'https://placehold.co/600x400',
    slug: 'erros-comuns-na-saboaria',
    progress: 0,
    lessons: [
      { id: 1, title: 'Introdução aos Erros Comuns na Saboaria', url: 'https://www.youtube.com/embed/x39O0bFVcqM', completed: false },
      { id: 2, title: 'Ponto Certo da Base e Uso Correto das Essências', url: 'https://www.youtube.com/embed/KFG01L1nJOo', completed: false },
      { id: 3, title: 'Sabonete Suando e Modo Correto de Secagem', url: 'https://www.youtube.com/embed/T3ZZAhqgiWg', completed: false },
      { id: 4, title: 'Ressecamento e Falta de Espuma', url: 'https://www.youtube.com/embed/_eE288DcPNM', completed: false },
    ],
  },
  {
    id: 3,
    title: 'Módulo 03 - Seu Primeiro Sabonete',
    description: 'Um passo a passo guiado para você criar seu primeiro sabonete artesanal do zero.',
    image: 'https://placehold.co/600x400',
    slug: 'seu-primeiro-sabonete',
    progress: 0,
    lessons: [
        { id: 1, title: 'Mão na Massa!', url: 'https://www.youtube.com/embed/vo0lwzl2aXA', completed: false },
        { id: 2, title: 'Desenformando o Sabonete', url: 'https://www.youtube.com/embed/JRXCk7Uc8k4', completed: false },
        { id: 3, title: 'Embalagem e Precificação', url: 'https://www.youtube.com/embed/fhmioW0P1aA', completed: false },
    ],
  },
  {
    id: 4,
    title: 'Módulo 04 - Sabonetes Decorativos',
    description: 'Técnicas para transformar seus sabonetes em verdadeiras obras de arte.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonetes-decorativos',
    progress: 0,
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/KNVkPdK55d8', completed: false },
        { id: 2, title: 'Fazendo o Sabonete Decorativo', url: 'https://www.youtube.com/embed/4NXL5wPwhCQ', completed: false },
        { id: 3, title: 'Desenformando o Sabonete Decorativo', url: 'https://www.youtube.com/embed/w1XiezRfuDQ', completed: false },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/4A97GuZ2aOI', completed: false },
    ],
  },
  {
    id: 5,
    title: 'Módulo 05 - Sabonetes Para Lembrancinhas',
    description: 'Crie sabonetes perfeitos para presentear em eventos e ocasiões especiais.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonetes-para-lembrancinhas',
    progress: 0,
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/P8pktqeEpvQ', completed: false },
        { id: 2, title: 'Fazendo Nosso Sabonete', url: 'https://www.youtube.com/embed/AylWaIgu778', completed: false },
        { id: 3, title: 'Desenformando nosso Sabonete', url: 'https://www.youtube.com/embed/KfQxmbhokkY', completed: false },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/oW1Pm-CO3fA', completed: false },
    ],
  },
  {
    id: 6,
    title: 'Módulo 06 - Sabonete Esfoliante',
    description: 'Aprenda a fazer sabonetes que limpam e renovam a pele com ingredientes naturais.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-esfoliante',
    progress: 0,
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/Osr2NNhg4YQ', completed: false },
        { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/embed/biKY2p7dHrU', completed: false },
        { id: 3, title: 'Desenformando', url: 'https://www.youtube.com/embed/BaUYrLlYNC0', completed: false },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/fhtJ7Lns_sg', completed: false },
    ],
  },
  {
    id: 7,
    title: 'Módulo 07 - Sabonete de Frutas',
    description: 'Incorpore o poder e os aromas das frutas em suas criações.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-de-frutas',
    progress: 0,
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/mCfs8uxxdGA', completed: false },
        { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/embed/VaTMghE8Ugk', completed: false },
        { id: 3, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/embed/D8TZdIWv86A', completed: false },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/xGE5VxrfdGs', completed: false },
    ],
  },
  {
    id: 8,
    title: 'Módulo 08 - Sabonete Fito Energético',
    description: 'Descubra como usar a energia das plantas para criar sabonetes com propósito.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-fito-energetico',
    progress: 0,
    lessons: [
      { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/CeSBrDagGRs', completed: false },
      { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/embed/1Licryb1ik4', completed: false },
      { id: 3, title: 'Aula Pratica', url: 'https://www.youtube.com/embed/1Licryb1ik4', completed: false },
      { id: 4, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/embed/1lzgaUJyaJI', completed: false },
      { id: 5, title: 'Precificação', url: 'https://www.youtube.com/embed/dDQjI1COqe0', completed: false },
    ],
  },
  {
    id: 9,
    title: 'Módulo 09 - Sabonete Terapêutico',
    description: 'Crie sabonetes com propriedades terapêuticas usando óleos essenciais e extratos naturais.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-terapeutico',
    progress: 0,
    lessons: [
        { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/vfwcQQLlhog', completed: false },
        { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/embed/Uf55mYcFb1Y', completed: false },
        { id: 3, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/embed/lSTVl3PQk18', completed: false },
        { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/KDKvMYRfBTQ', completed: false },
    ],
  },
  {
    id: 10,
    title: 'Módulo 10 - Sabonete Vegano',
    description: 'Aprenda a fazer sabonetes de alta qualidade sem nenhum ingrediente de origem animal.',
    image: 'https://placehold.co/600x400',
    slug: 'sabonete-vegano',
    progress: 0,
    lessons: [
      { id: 1, title: 'Introdução', url: 'https://www.youtube.com/embed/u-NMGjMpDCg', completed: false },
      { id: 2, title: 'Aula Pratica', url: 'https://www.youtube.com/embed/_lqbshzHVEg', completed: false },
      { id: 3, title: 'Desenformando e Embalando', url: 'https://www.youtube.com/embed/zqmqxlvyXCI', completed: false },
      { id: 4, title: 'Precificação', url: 'https://www.youtube.com/embed/hSttFBuI-jM', completed: false },
    ],
  },
];

export const bonusContent: ContentItem[] = [
  {
    id: 1,
    title: 'Bônus: Embalagens Criativas',
    description: 'Ideias para valorizar seus sabonetes com embalagens encantadoras e sustentáveis.',
    image: 'https://placehold.co/600x400',
    slug: 'embalagens-criativas',
    progress: 50,
    lessons: [
      { id: 1, title: 'Técnicas de Embrulho com Tecido (Furoshiki)', url: 'https://www.youtube.com/embed/placeholder', completed: false },
      { id: 2, title: 'Criação de Rótulos e Cintas de Papel', url: 'https://www.youtube.com/embed/placeholder', completed: false },
      { id: 3, title: 'Caixas e Sacolas Personalizadas', url: 'https://www.youtube.com/embed/placeholder', completed: false },
    ],
  },
  {
    id: 2,
    title: 'Bônus: Calculadora de Saboaria',
    description: 'Uma ferramenta interativa para ajudar você a criar suas próprias receitas com precisão.',
    image: 'https://placehold.co/600x400',
    slug: 'calculadora-de-saboaria',
    progress: 100,
    lessons: [
        { id: 1, title: 'Entendendo a Calculadora', url: 'https://www.youtube.com/embed/placeholder', completed: false },
        { id: 2, title: 'Simulando sua Primeira Receita', url: 'https://www.youtube.com/embed/placeholder', completed: false },
    ],
  },
  {
    id: 3,
    title: 'Bônus: Guia de Fornecedores',
    description: 'Uma lista selecionada de fornecedores de confiança para seus ingredientes e materiais.',
    image: 'https://placehold.co/600x400',
    slug: 'guia-de-fornecedores',
    progress: 0,
    lessons: [
        { id: 1, title: 'Onde Comprar Óleos e Manteigas', url: 'https://www.youtube.com/embed/placeholder', completed: false },
        { id: 2, title: 'Fornecedores de Embalagens e Moldes', url: 'https://www.youtube.com/embed/placeholder', completed: false },
    ],
  },
];
